x-app-base: &app-base
  build:
    context: .
    target: staging
    network: host
  image: task_manager_img:latest
  volumes:
    - .:/app
    - /app/.venv
  env_file:
    - .env.staging
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started

services:
  app:
    <<: *app-base
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery_worker:
    <<: *app-base
    container_name: celery_worker
    command: celery --app config.celery worker -l info

  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.staging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus-monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - "9100:9100"
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./prometheus-monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./prometheus-monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      # - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - "3000:3000"
    restart: unless-stopped

  # alertmanager:
  #   image: prom/alertmanager:latest
  #   container_name: alertmanager
  #   volumes:
  #     - ./prometheus-monitoring/alertmanager:/etc/alertmanager
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  #   ports:
  #     - "9093:9093"
  #   networks:
  #     - monitoring
  #   restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data: {}
  grafana_data: {}